// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bffnmvwcehwrylqvldhg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJmZm5tdndjZWh3cnlscXZsZGhnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg3MjM2NzQsImV4cCI6MjA3NDI5OTY3NH0.RIaExz6VTZ7UtVlwraHkKcUK-sZV0J-X-_u-7CwKGso";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});